site_name: Documentación del Proyecto

docs_dir : docs_src

nav:
  - Inicio : index.md
  - Manual de Usuario: actividad_2/Manual_de_Usuario.md
  - Guía de Referencia: actividad_2/Guia_de_Referencia.md
  - Guía de Instalación: actividad_2/Guia_de_Instalacion.md

theme:
  name: material

markdown_extensions:
  - toc:
      permalink: true